Refactor code to use Lombok's @Slf4j for logging
josdem/jmetadata pull request #41
Opened 2024-12-11 21:16 UTC by Lemeri123

This pull request refactors the code to replace manual logger initialization using LoggerFactory with Lombok's @Slf4j annotation and removed the manual Logger initialization (private static final Logger log = LoggerFactory.getLogger(LoginController.class);). #37 

cc.
@josdem

2024-12-11 21:18 UTC, Lemeri123 commented
@josdem let me know if at all there are changes I need to make

2024-12-11 22:47 UTC, josdem requested changes
Awesome work @Lemeri123 , just a small change before merge.

2024-12-11 22:47 UTC, josdem commented on build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter'
We already have Lombok dependency added, please take a look at lines:
https://github.com/josdem/jmetadata/blob/9105b7256fad7e543ce1312d0d8ef8f50239485d/build.gradle#L57L58

2024-12-11 22:48 UTC, josdem commented
@all-contributors please add @Lemeri123 for code

2024-12-12 16:11 UTC, josdem approved these changes
Thank you for doing suggested changes 👍

2024-12-12 16:11 UTC, merged